version: '3'

services:
  dtest:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: skipglide/dtest:latest
    networks:
      - d_net
    expose:
      - 8000
    volumes:
      - .:/code
      - ./static:/usr/share/nginx/html/static
  nginx:
    image: skipglide/nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    networks:
      - d_net
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx
      - ./static:/usr/share/nginx/html/static

networks:
  d_net:
    external: true