version: '3'

services:
  dtest:
    build: .
    command: python dtest/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    entrypoint: "/code/entrypoint.sh"
    ports:
      - "8000:8000"
