version: '3'

services:
  dtest:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: skipglide/dtest:latest
    command: python dtest/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    entrypoint: /code/entrypoint.sh
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    #build: ./docker/nginx/Dockerfile
    #command: echo ""
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d